# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.guest = :linux
  config.vm.box = "fedora/24-cloud-base"
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D10036"

  # Configure for yunibase
  config.vm.box_check_update = true
  # Can't do any automount but add it anyway
  config.vm.synced_folder "../../..", "/yunibase", disabled: true
  # Disable the default share
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision "shell", inline: <<-SHELL
dnf update -y
dnf install -y docker cmake make
systemctl enable docker
systemctl start docker
  SHELL
end

