FROM microsoft/windowsservercore:1709
WORKDIR /
ADD http://cygwin.com/setup-x86_64.exe /
RUN setup-x86_64.exe -s http://ftp.iij.ad.jp/pub/cygwin -R c:\\cyg64 -l c:\\cache64 -B -v -q -N -d -g -P  libiconv-devel,libisl10,cloog-isl,cmake,git,gcc,make,gcc-g++,automake,autoconf,libtool,libgmp-devel,libonig-devel,flex,gettext-devel,pkg-config,libunistring-devel,libffi-devel,libgc-devel,texinfo,zlib-devel
